### ISSUE TITLE
Auto update needs to migrate from a personal account to sasview

### ISSUE THREAD

**Issue by butlerpd** [SasView/saspubs#1]
currently the code being used is not from this repo but from Krzywon personal repo.  Further the job is running under Krzywon's personal account on the UTK server rather than the sasbot.

This should be updated to be fully integrated into the community project. Probably Jeff will need to work with Wojciech who has done this with the marketplace?

**Comment by krzywon** [comment]
The saspubs on the UTK server is fetching from https://github.com/sasview/saspubs.git as confirmed with 'git config --get remote.origin.url'

The job is running under my account as was noted in https://github.com/SasView/sasview/issues/617 as one of the last couple of items needed to finish.

**Comment by krzywon** [comment]
The changes Andrew made to saspubs weren't added to the publications.md update, so the changes Paul made on sasview.github.io were overwritten, so that is an issue.

**Comment by butlerpd** [comment]
More info:

Actually, @butlerpd was an idiot and did what he explained to others not to do: change the md page directly ... which indeed was overwritten within 5 minutes.  Once we figured out what had happened (by looking at commits to github.io) @ajj worked to figure out hot to change the code generating the page.  When that never updated correctly he determined that what was being pushed to github.io appeared to be coming from krzywon/saspubs indicating a parallel repo was somehow being pulled in?  trying to look at the code running on the danse server revealed the issue apparently reported in  SasView/sasview#617

**Comment by ajj** [comment]
@krzywon - what is the status on this and SasView/sasview#617

**Comment by krzywon** [comment]
I disabled automatic publication updates on the DANSE server while I work on this. The updates will resume sometime the next few days.

**Comment by krzywon** [comment]
I now have sasview-bot account performing the push instead of me. The first auto-update happened with commit https://github.com/SasView/sasview.github.io/commit/d159f939dfb71f57386ef6def9debb2aeff699c8
